<?php

declare(strict_types=1);

namespace App\Services\Profile;

class ProfileBuilder
{
    /**
     * @var array<string, string>
     */
    private const CONTACT_LABELS = [
        'name' => 'Nombre',
        'email' => 'Email',
        'phone' => 'Teléfono',
        'location' => 'Ubicación',
        'linkedin' => 'LinkedIn',
        'github' => 'GitHub',
    ];

    public function __construct(private readonly EnglishLevelDetector $englishLevelDetector) {}

    /**
     * @param  array{
     *     contact: array<string, string|null>,
     *     headline: string|null,
     *     summary: string|null,
     *     experience: array<int, string>,
     *     skills: array<int, string>,
     *     education: array<int, string>,
     *     languages: array{items: array<int, string>, english_level: string|null},
     *     certifications: array<int, string>,
     * }  $profile
     */
    public function toMarkdown(array $profile): string
    {
        $lines = [];
        $lines[] = '# '.($profile['headline'] ?? $profile['contact']['name'] ?? 'Perfil profesional');
        $lines[] = '';

        $lines[] = '## Contacto';
        foreach ($this->contactLines($profile['contact']) as $line) {
            $lines[] = "- {$line}";
        }
        $lines[] = '';

        $lines[] = '## Resumen';
        $lines[] = $profile['summary'] ?? 'No especificado';
        $lines[] = '';

        $lines[] = '## Experiencia';
        $lines = [...$lines, ...$this->bulletedOrEmpty($profile['experience'])];
        $lines[] = '';

        $lines[] = '## Skills';
        $lines = [...$lines, ...$this->bulletedOrEmpty($profile['skills'])];
        $lines[] = '';

        $lines[] = '## Educación';
        $lines = [...$lines, ...$this->bulletedOrEmpty($profile['education'])];
        $lines[] = '';

        $lines[] = '## Idiomas';
        $lines = [...$lines, ...$this->bulletedOrEmpty($profile['languages']['items'])];
        $lines[] = '';

        $lines[] = '## Certificaciones';
        $lines = [...$lines, ...$this->bulletedOrEmpty($profile['certifications'])];

        return trim(implode("\n", $lines))."\n";
    }

    /**
     * Re-parses a `perfil.md` file previously generated by {@see toMarkdown()} back into
     * the same structured shape, by reading its `##` section headers. Deterministic,
     * no AI involved.
     *
     * @return array{
     *     contact: array<string, string|null>,
     *     headline: string|null,
     *     summary: string|null,
     *     experience: array<int, string>,
     *     skills: array<int, string>,
     *     education: array<int, string>,
     *     languages: array{items: array<int, string>, english_level: string|null},
     *     certifications: array<int, string>,
     * }
     */
    public function fromMarkdown(string $markdown): array
    {
        $lines = preg_split('/\r\n|\r|\n/', $markdown) ?: [];

        $headline = null;
        $sections = [];
        $currentSection = null;

        foreach ($lines as $line) {
            $trimmed = trim($line);

            if ($trimmed === '') {
                continue;
            }

            if ($headline === null && str_starts_with($trimmed, '# ')) {
                $headline = trim(substr($trimmed, 2));

                continue;
            }

            if (str_starts_with($trimmed, '## ')) {
                $currentSection = $this->normalizeHeading(trim(substr($trimmed, 3)));
                $sections[$currentSection] ??= [];

                continue;
            }

            if ($currentSection !== null) {
                $sections[$currentSection][] = preg_replace('/^-\s*/', '', $trimmed);
            }
        }

        $summaryLines = $this->resolveList($sections, 'resumen');
        $summary = implode("\n", $summaryLines);
        $idiomas = $this->resolveList($sections, 'idiomas');

        return [
            'contact' => $this->parseContactLines($sections['contacto'] ?? []),
            'headline' => $headline,
            'summary' => $summary !== '' ? $summary : null,
            'experience' => $this->resolveList($sections, 'experiencia'),
            'skills' => $this->resolveList($sections, 'skills'),
            'education' => $this->resolveList($sections, 'educacion'),
            'languages' => [
                'items' => $idiomas,
                'english_level' => $this->englishLevelDetector->detect($idiomas),
            ],
            'certifications' => $this->resolveList($sections, 'certificaciones'),
        ];
    }

    /**
     * @param  array<string, string|null>  $contact
     * @return array<int, string>
     */
    private function contactLines(array $contact): array
    {
        $lines = [];

        foreach (self::CONTACT_LABELS as $key => $label) {
            if (! empty($contact[$key])) {
                $lines[] = "{$label}: {$contact[$key]}";
            }
        }

        return $lines;
    }

    /**
     * @param  array<int, string>  $lines
     * @return array<string, string|null>
     */
    private function parseContactLines(array $lines): array
    {
        $labelToKey = array_flip(self::CONTACT_LABELS);
        $contact = array_fill_keys(array_keys(self::CONTACT_LABELS), null);

        foreach ($lines as $line) {
            if (! str_contains($line, ':')) {
                continue;
            }

            [$label, $value] = array_map('trim', explode(':', $line, 2));
            $key = $labelToKey[$label] ?? null;

            if ($key !== null) {
                $contact[$key] = $value;
            }
        }

        return $contact;
    }

    /**
     * @param  array<string, array<int, string>>  $sections
     * @return array<int, string>
     */
    private function resolveList(array $sections, string $key): array
    {
        $lines = $sections[$key] ?? [];

        return $lines === ['No especificado'] ? [] : $lines;
    }

    /**
     * @param  array<int, string>  $items
     * @return array<int, string>
     */
    private function bulletedOrEmpty(array $items): array
    {
        if ($items === []) {
            return ['No especificado'];
        }

        return array_map(fn (string $item) => "- {$item}", $items);
    }

    private function normalizeHeading(string $heading): string
    {
        $translit = strtr(mb_strtolower($heading), [
            'á' => 'a', 'é' => 'e', 'í' => 'i', 'ó' => 'o', 'ú' => 'u', 'ñ' => 'n',
        ]);

        return match ($translit) {
            'contacto' => 'contacto',
            'resumen' => 'resumen',
            'experiencia' => 'experiencia',
            'skills' => 'skills',
            'educacion' => 'educacion',
            'idiomas' => 'idiomas',
            'certificaciones' => 'certificaciones',
            default => $translit,
        };
    }
}
